package profiles

import (
	"context"
	"fmt"
	"strings"
	"time"

	"aws-profile-manager/internal/core"
	"aws-profile-manager/internal/generators"
	"aws-profile-manager/internal/logging"
	"aws-profile-manager/internal/schema"
	"aws-profile-manager/internal/task"
)

// =============================================================================
// MARKER DETECTION
// =============================================================================

// detectMarkers finds the line numbers of start and end markers.
//
// Parameters:
//   - lines: Config file lines to search
//   - startMarker: Start marker text to find
//   - endMarker: End marker text to find
//
// Returns:
//   - markerPosition: Position information including line numbers and found status
func detectMarkers(lines []string, startMarker, endMarker string) markerPosition {
	startLine := -1
	endLine := -1

	for i, line := range lines {
		if strings.Contains(line, startMarker) {
			startLine = i
		}
		if strings.Contains(line, endMarker) {
			endLine = i
		}
	}

	return markerPosition{
		StartLine: startLine,
		EndLine:   endLine,
		Found:     startLine != -1 && endLine != -1,
	}
}

// =============================================================================
// SPACING AND SECTION BUILDING
// =============================================================================

// addManagedSection adds the managed section with proper formatting.
//
// This ensures consistent formatting:
//   - Exactly ONE blank line before start marker (if content above exists)
//   - Start marker followed by a warning block
//   - Optional metadata lines (version, timestamp) controlled by cfg
//   - Exactly ONE blank line after warning
//   - Managed content
//   - Exactly ONE blank line before end marker
//   - End marker
//
// Parameters:
//   - lines: Existing lines to append to
//   - managedContent: Content to add between markers
//   - startMarker: Start marker text
//   - endMarker: End marker text
//   - cfg: Config carrying IncludeTimestamp and IncludeVersion flags
//
// Returns:
//   - []string: Lines with managed section added
func addManagedSection(lines []string, managedContent, startMarker, endMarker string, cfg Config) []string {
	// Ensure exactly one blank line before start marker
	// Remove any trailing blank lines first
	for len(lines) > 0 && lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	// Add one blank line if there's content above
	if len(lines) > 0 {
		lines = append(lines, "")
	}

	// Add start marker with warning message
	lines = append(lines, startMarker)
	lines = append(lines, "#")
	lines = append(lines, "# WARNING: This section is automatically managed by AWS Profile Manager.")
	lines = append(lines, "# Any manual changes will be overwritten on the next profile installation.")
	lines = append(lines, "# To preserve custom profiles, add them OUTSIDE this managed section.")
	lines = append(lines, "#")

	// Optional metadata lines — only written when enabled in settings.
	if cfg.IncludeVersion {
		lines = append(lines, fmt.Sprintf("# Generated by AWS Profile Manager v%s", core.AppVersion))
	}
	if cfg.IncludeTimestamp {
		// Use the friendly local-timezone format consistent with the rest of the app.
		lines = append(lines, fmt.Sprintf("# Generated at %s", core.FormatFriendlyDateTimeWithZone(time.Now())))
	}

	lines = append(lines, "")

	// Add managed content
	contentLines := strings.Split(managedContent, "\n")
	lines = append(lines, contentLines...)

	// Ensure exactly one blank line before end marker
	// Remove any trailing blank lines from managed content
	for len(lines) > 0 && lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	// Add exactly one blank line
	lines = append(lines, "")

	// Add end marker
	lines = append(lines, endMarker)

	return lines
}

// buildFinalConfig constructs the final three-section config file.
//
// This preserves user content outside markers and replaces the managed section.
// Ensures proper spacing between all sections.
//
// Parameters:
//   - existingLines: Current config file lines
//   - managedContent: New managed section content (without markers)
//   - markers: Marker position information
//   - startMarker: Start marker text
//   - endMarker: End marker text
//   - cfg: Config carrying metadata flags (IncludeTimestamp, IncludeVersion)
//
// Returns:
//   - []string: Final config file lines
func buildFinalConfig(
	existingLines []string,
	managedContent string,
	markers markerPosition,
	startMarker, endMarker string,
	cfg Config,
) []string {
	var finalLines []string

	// Step 1: Add content above managed section
	if !markers.Found {
		// No markers exist - include all existing content
		finalLines = append(finalLines, existingLines...)
	} else {
		// Markers exist - include content before start marker
		finalLines = append(finalLines, existingLines[:markers.StartLine]...)
	}

	// Step 2: Add managed section with markers
	finalLines = addManagedSection(finalLines, managedContent, startMarker, endMarker, cfg)

	// Step 3: Add content below managed section (if markers existed)
	if markers.Found && markers.EndLine+1 < len(existingLines) {
		// Add blank line before below content if it's not already blank
		if len(existingLines[markers.EndLine+1:]) > 0 && existingLines[markers.EndLine+1] != "" {
			finalLines = append(finalLines, "")
		}
		finalLines = append(finalLines, existingLines[markers.EndLine+1:]...)
	}

	return finalLines
}

// =============================================================================
// PROFILE COUNTING
// =============================================================================

// countProfiles calculates the total number of profiles in a ProfileCollection.
//
// Uses generators to get accurate counts since they know exactly how many
// profiles they will create. Discards generated content, keeps only statistics.
//
// Parameters:
//   - collection: ProfileCollection to count
//
// Returns:
//   - int: Total number of profiles that would be generated
func countProfiles(collection *schema.ProfileCollection) int {
	if collection == nil {
		return 0
	}

	// Use generators to get accurate counts (discard content)
	_, ssoStats, _ := generators.GenerateSsoProfiles(context.Background(), collection, task.NoOpReporter{})
	_, iamStats, _ := generators.GenerateIamProfiles(context.Background(), collection, task.NoOpReporter{})
	_, assumeRoleStats, _ := generators.GenerateAssumeRoleProfiles(context.Background(), collection, task.NoOpReporter{})
	_, genericStats, _ := generators.GenerateGenericProfiles(context.Background(), collection, task.NoOpReporter{})

	return ssoStats.ProfilesWritten + iamStats.ProfilesWritten +
		assumeRoleStats.ProfilesWritten + genericStats.ProfilesWritten
}

// countSsoSessions calculates the number of SSO sessions in a ProfileCollection.
//
// Uses the SSO generator to get accurate session count since the generator
// knows exactly how many sessions it creates.
//
// Parameters:
//   - collection: ProfileCollection to count
//
// Returns:
//   - int: Total number of SSO sessions
func countSsoSessions(collection *schema.ProfileCollection) int {
	if collection == nil {
		return 0
	}

	if len(collection.Organizations) == 0 {
		return 0
	}

	// Use generator to get accurate session count
	_, stats, _ := generators.GenerateSsoProfiles(context.Background(), collection, task.NoOpReporter{})
	return stats.SessionsWritten
}

// calculateProfileCounts calculates total profiles and SSO sessions in schema.
//
// This provides comprehensive counts for all profile types and SSO sessions.
// Used for dry-run mode and result statistics.
//
// Parameters:
//   - s: Schema to count
//
// Returns:
//   - profileCount: Total number of profiles
//   - sessionCount: Total number of SSO sessions
func calculateProfileCounts(s *schema.Schema) (int, int) {
	if s == nil || s.Managed == nil {
		return 0, 0
	}

	profileCount := countProfiles(s.Managed)
	sessionCount := countSsoSessions(s.Managed)

	return profileCount, sessionCount
}

// hasProfiles checks if a ProfileCollection contains any profiles.
//
// Parameters:
//   - collection: ProfileCollection to check
//
// Returns:
//   - bool: true if collection has at least one profile of any type
func hasProfiles(collection *schema.ProfileCollection) bool {
	if collection == nil {
		return false
	}

	return len(collection.Organizations) > 0 ||
		len(collection.IamUsers) > 0 ||
		len(collection.AssumeRoleChains) > 0 ||
		len(collection.GenericProfiles) > 0
}

// =============================================================================
// CONTENT COMPARISON
// =============================================================================

// hasContentChanged compares existing and new lines to detect changes.
//
// This performs a line-by-line comparison to determine if the file
// content would actually change. Used to avoid unnecessary writes.
//
// Parameters:
//   - existingLines: Current config file lines
//   - newLines: New config file lines
//
// Returns:
//   - bool: true if content is different
func hasContentChanged(existingLines, newLines []string) bool {
	if len(existingLines) != len(newLines) {
		return true
	}

	for i := range existingLines {
		if existingLines[i] != newLines[i] {
			return true
		}
	}

	return false
}

// =============================================================================
// VALIDATION
// =============================================================================

// validateSchema performs comprehensive schema validation.
//
// Checks that schema is not nil, has managed section, and contains profiles.
// Security: Validate at trust boundary (when receiving data from external sources).
//
// Parameters:
//   - s: Schema to validate
//
// Returns:
//   - error: Detailed error if validation fails, nil if valid
func validateSchema(s *schema.Schema) error {
	if s == nil {
		return logging.Log.ErrorfWithDetails("schema is required", nil)
	}

	// Validate schema structure
	if err := s.Validate(); err != nil {
		return logging.Log.ErrorfWithDetails("invalid schema", err)
	}

	// Check for profiles
	if s.Managed == nil {
		return logging.Log.ErrorfWithDetails("schema contains no profiles to install (empty managed section may indicate file corruption)", nil)
	}

	if !hasProfiles(s.Managed) {
		return logging.Log.ErrorfWithDetails("schema contains no profiles to install (empty managed section may indicate file corruption)", nil)
	}

	return nil
}
