// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package bundled

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/logo.png
var ResourceLogoData []byte
var ResourceLogo = &fyne.StaticResource{
	StaticName:    "assets/logo.png",
	StaticContent: ResourceLogoData,
}

//go:embed assets/logo-dark-mode.png
var ResourceLogoDarkModeData []byte
var ResourceLogoDarkMode = &fyne.StaticResource{
	StaticName:    "assets/logo-dark-mode.png",
	StaticContent: ResourceLogoDarkModeData,
}
